services:
  - type: web
    name: mgr-whatsapp-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python whatsapp_test.py
    envVars:
      - key: WHATSAPP_TOKEN=EAAN8uTyaqcgBRTMKYkMmhNWQrtqIEKZAvpWEX5ZCnFCyN2XZAD3g21ekcGT1D0ZA7N4lzWV01dR9ovSmNhyEAORm1HIfQt9NppIZCKg6THkPJeWtUNCZCIF9EHmqnZCqgoGD9cEnbX6KsYLhSC02b3hNFSSqMsg5LuGbgbNpM9CCnLPrFzyfoIdwZBFMRcgJsBTdAqVVnZA5l5djFLaQVidvsZBVCEZBWFLxZBe6nAnFWGxvsGLXzanE1QZDZD
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID=1082079474997329
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        value: mgr-teste
      - key: GEMINI_API_KEY=pWIQG969OLwWzU0jQENDVlnbCLFzf0nnMvNTdL5RuwQOBRdmK2Wctb5q
        sync: false
      - key: GOOGLE_AI_MODEL
        value: gemma-3-27b-it
      - key: TTS_SPEED
        value: '1.5'
